### PR TITLE
Added proxy support and updated docs as needed.

### PR DESCRIPTION
**Pull request by iJohnMaged**
Amazing job on this project! After Twint died after recent twitter policy update I was looking around for a scraper as a part of my project and I found yours and it seems to be working fine after the policy update.

However for my use case, I need to use proxies which I didn't see supported, while implementing it manually is easy enough but I think it might be a common use case so I added a `ProxyClientRequests` class that supports proxies, as well as additional options for requests depending on the proxy needs (certificate, verifications, etc.)

### CODE REVIEW

**Comment by iJohnMaged** [comment]
I added tests, however testing with proxy set to `None` since I don't have a "public" proxy that I can put on git. 👍 
I also added exceptions.

**Comment by markowanga** [comment]
Hej, thank you 😊, it is my first Pull Request from other user 😁. I want to try adding tor proxy to run tests -- it is 100% of coverage, but I think it is important (when it's possible to test it). In the other hand this means that every user need to tor proxy to test app -- I will consider about this. Do you care about adding changes quickly? (I will add changes this day -- I've got 9 a.m. and start work already)

**Comment by markowanga** [comment]
Code is super, I recently started programming in python (previous I use Java and Kotlin) -- so I don't have many python experience. If you see that my code needs to change sth, please add issue or write in PR comment.

**Review by markowanga — DISMISSED** [review]
Thank you 😉

**Review by markowanga — APPROVED** [review]

**Comment by iJohnMaged** [comment]
> Code is super, I recently started programming in python (previous I use Java and Kotlin) -- so I don't have many python experience. If you see that my code needs to change sth, please add issue or write in PR comment.

I've been coding in Python for a quite while now , I think you could utilize more dataclasses in a better way but it doesn't matter if you're not using them at all, overall the code structure seems pretty decent to me! Well organized and tested 👍 I'll definitely be adding more PRs soon since I'm working on a project that heavily relies on Twitter scraping without spending a fortune. :D 

Great job! 👍

**Comment by iJohnMaged** [comment]
> 
> 
> Hej, thank you 😊, it is my first Pull Request from other user 😁. I want to try adding tor proxy to run tests -- it is 100% of coverage, but I think it is important (when it's possible to test it). In the other hand this means that every user need to tor proxy to test app -- I will consider about this. Do you care about adding changes quickly? (I will add changes this day -- I've got 9 a.m. and start work already)

I'm interested in doing more PRs soon! I'm not sure the best strategy to test that kind of thing, from my experience it also will depend on the proxy type and tor had many problems with Twitter for my usage.

**Pull request merged**
